modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
#issueTrackerURL=""

[[mods]]
    modId="chest_minecart_sound"
    version="0.0.1"
    displayName="Chest Minecart Sound"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
A mod to play the chest opening and close sounds for chest minecarts'''

[[dependencies.chest_minecart_sound]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chest_minecart_sound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"