modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL=""

[[mods]]
    modId="chest_minecart_sound"
    version="${file.jarVersion}"
    displayName="Chest Minecart Sound"
    #updateJSONURL=""
    authors="Grimmauld"
    description='''
A mod to play the chest opening and close sounds for chest minecarts'''

[[dependencies.chest_minecart_sound]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chest_minecart_sound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"